### ISSUE TITLE
detect toxic content to improve online conversations

### ISSUE THREAD

**Issue by vinhyenvodoi98** [tienthegainz/ImageAutoCaptioning#1]
i want to build a system can detect toxic content to improve online conversations . what's the idea  for this problem ?

**Comment by tienthegainz** [comment]
Thanks for your question. Not an expert in NLP but I think firstly, I think you should consider what is the toxic content? Based on the situation or something else. Most of modern system, for example, in game, banned certain words like: f*ck. Some words can be ambigous such as: "Mẹ" used in both normal sentence and swear. But still, I think some sequence model like LSTM could resolve your problem. But to build it, you may have to find it yourself.

**Comment by vinhyenvodoi98** [comment]
thanks for your suggestions ,that was useful
